import { type Express } from 'express';
import type { ServerDeps } from '../deps';
import { initAuditLogsController } from './auditLogs';
import { initBanksController } from './banks';
import { initBusinessesController } from './businesses';
import { initCategoriesController } from './categories';
import { initClientsController } from './clients';
import { initCurrenciesController } from './currencies';
import { initImportExportController } from './importExport';
import { initInvoicesController } from './invoices';
import { initItemsController } from './items';
import { initLayoutsController } from './layouts';
import { initOfficesController } from './offices';
import { initPresetsController } from './presets';
import { initRolesController } from './roles';
import { initSettingsController } from './settings';
import { initStyleProfilesController } from './styleProfiles';
import { initUnitsController } from './units';
import { initUsersController } from './users';

export const initControllers = (app: Express, deps: ServerDeps) => {
  initImportExportController(app, deps);
  initLayoutsController(app, deps);
  initBusinessesController(app, deps);
  initCategoriesController(app, deps);
  initClientsController(app, deps);
  initInvoicesController(app, deps);
  initItemsController(app, deps);
  initSettingsController(app, deps);
  initStyleProfilesController(app, deps);
  initUnitsController(app, deps);
  initCurrenciesController(app, deps);
  initBanksController(app, deps);
  initPresetsController(app, deps);
  initOfficesController(app, deps);
  initRolesController(app, deps);
  initUsersController(app, deps);
  initAuditLogsController(app, deps);
};
